### ISSUE TITLE
Add a /docs service

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/pilot-hubs#163]
@choldgraf and others have been asking for a way to host hub-specific documentation controlled by the hub champions (and instructors). This is a great idea! We should use jupyter-book (or sphinx in general) for these docs, in-line with what most of our community uses. 

We'd need to do the following to make it happen:

1. Make a [sphinx-autobuild](https://pypi.org/project/sphinx-autobuild/) container. This should do sphinx builds on a git repository mounted into it & serve them to the wider world.
2. Addition to our base helm template that create a kubernetes Deployment with the sphinx-autobuild container. The docs repo we want to use should be mounted as git repository there, similar to how the hub templates are mounted into the hub pod
3. Make a Service to point to the deployment
4. Add the Deployment+Service as a jupyterhub service, named 'docs'. We can tell the hub to proxy '/docs' requests to this service.

If / when a hub wants to serve a git repository at /docs, we can just point this JupyterHub service at their repository.

**Comment by choldgraf** [comment]
I'm +1 on the idea - any reason that we're making this Sphinx-specific, as opposed to the earlier thought of just asking them to point to a repo with SSG-style HTML files in it? E.g., we could also give people documentation (maybe support?) in how to use github actions to generate HTML and dump it on a repo's branch, and then the hub's job would just be to serve those HTML files rather than build a Sphinx site.

**Comment by yuvipanda** [comment]
@choldgraf ah, I see. I was making it sphinx-specific purely so users don't have to deal with GitHub actions. Plus, if they can dump the content elsewhere (github pages, or netlify), why keep it in /docs? Rather than just redirect them to the other website?

But, let's start with just serving content from a git repo in /docs, and go from there.

So new steps for this would be to:

1. Use a traefik container configured to files locally from a git repository
2. Addition to our base helm template that create a kubernetes Deployment with the traefik container. The docs repo we want to use should be mounted as git repository there, similar to how the hub templates are mounted into the hub pod. The configuration should be injected as a configmap
3. Make a Service to point to the deployment
4. Add the Deployment+Service as a jupyterhub service, named 'docs'. We can tell the hub to proxy '/docs' requests to this service.

**Comment by choldgraf** [comment]
Yeah - I think there are benefits to asking users to rely on other common services for building docs and such - it makes it easier for them to not become "dependent" on 2i2c, and then we also don't have to worry about things like log generation and error reporting (e.g., what if building docs throws an error, as it often does? what if building docs requires significant computation?)

**Comment by yuvipanda** [comment]
So the workflow would be:

1. They use a GitHub repo to write their docs
2. They setup GH Actions or similar to publish to gh-pages branch
2. They give us the github URL
3. We clone gh-pages and serve it.

The main advantage I could see is that we can assume that there is a a hub at `/`, so you can build docs that link to the right hub / have thebe do the right thing.

**Comment by consideRatio** [comment]
@yuvipanda I struggled a bit to understand [the Service documentation of JupyterHub](https://jupyterhub.readthedocs.io/en/stable/api/service.html?highlight=services), can you help me verify/correct/complement my understanding?

We can while configuring JupyterHub with an external service, make it also prepare its configurable proxy with a custom route, such as /docs, besides the default one which is /services/service-name no matter what if we also provide another route?

**Comment by yuvipanda** [comment]
> Having it as a JupyterHub external service doesn't imply JupyterHub based authentication right? Which means, this hosted documentation will be public? I figure it's not that hard to add a auth proxy using HubAuth if needed, but mostly wanted to confirm my understanding.

Yes, it will be public - for now, at least. I think adding an authenticated option here would be *brilliant* and open up more use cases. Do you know of any pre-existing proxy that just does HubAuth as a service?

**Comment by consideRatio** [comment]
I've not explored this yet, but is my understanding correct that JupyterHub can act as an OAuth2 provider?

Looking at [jupyterhub's documentation about HubOAuth](https://jupyterhub.readthedocs.io/en/stable/api/services.auth.html) I'm not confident. How to generate a client_secret / client_id? How does the JupyterHub service's api-token relate to all of this if it does in any way?

I have used a oauth2-proxy deployment + nginx-ingress controller with some annotations to do some magic in the past.

```yaml
   # An Ingress resource's annotation of a documentation
   # webserver that I wanted to protect with OAuth2 based authentication

    # auth-url / auth-signing:
    #   ref: https://kubernetes.github.io/ingress-nginx/examples/auth/oauth-external-auth/
    nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
    # configuration-snippet:
    #   To ensure /docs redirect to /docs/ which help the browser evaluate
    #   relative paths links to /docs/something instead of /something.
    #
    #   ref: https://github.com/kubernetes/ingress-nginx/issues/646#issue-224161025
    nginx.ingress.kubernetes.io/configuration-snippet: rewrite ^(/docs)$ $1/ permanent;
    # Disabled configuration:
    #   Using nginx-ingress-controller to modify the path beforing proxying it
    #   doesn't work so well it seems. It does as it should when we declare the
    #   path as /docs but not as /docs(/|$)(.*) which would be required for
    #   version 0.22.0+ and we currently are at 0.21.0. To ensure stability, I
    #   opt to let the actual webserver handle this in its nginx configuration
    #   instead with a rewrite directive.
    #
    # # rewrite-target:
    # #   ref: https://kubernetes.github.io/ingress-nginx/examples/rewrite/#examples
    # nginx.ingress.kubernetes.io/rewrite-target: /$2
    #
```

## References
- https://oauth2-proxy.github.io/oauth2-proxy/
- https://github.com/oauth2-proxy/oauth2-proxy
- https://kubernetes.github.io/ingress-nginx/examples/auth/oauth-external-auth/
