### ISSUE TITLE
Logout on JMTE redirected to Grenoble

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/pilot-hubs#447]
# Summary

Logging out from JupyterHub on hub.jupytearth.org redirects users to the wrong location in the end.

This is a redirection chain observed.

1. https://hub.jupytearth.org/hub/logout
2. https://2i2c.us.auth0.com/v2/logout?client_id=JptUUZT5RgWmjsLGYvcVS4CWvLsVptYt&returnTo=https://grenoble.2i2c.cloud
3. https://grenoble.2i2c.cloud

I observe that the client_id relates to the `prod` application rather than the `jmte` application that I registered, and that `grenoble` was the first logout url listed among the allowed logout urls. This is probably related. Is the deployer script not using the `jmte` application for logout stuff, only during login stuff?

It seems like the following code from the `class Hub` definition is using the `name` entry on the listed Hub. I guess I expected it to use the cluster name with regards to authentication rather then the hub name within the cluster.

```yaml
# This name is used during /hub/login
name: jmte
provider: none
hubs:
  # This name is used during /hub/logout
  - name: prod
    # ...
```

https://github.com/2i2c-org/pilot-hubs/blob/f68da3c2e65da1c8ae6df95aa32e4d9d7d897fd6/deployer/hub.py#L250-L251

**Comment by yuvipanda** [comment]
uh-oh, I think this is because we only use the 'name' parameter when creating & referencing OAuth clients!!! We should instead perhaps use the domain name?

**Comment by GeorgianaElena** [comment]
But I still don't understand why the `redirectTo` query of the logout url somehow ended up being the `grenoble` one, since these are built are built using the domain name :exploding_head:  

https://github.com/2i2c-org/pilot-hubs/blob/f68da3c2e65da1c8ae6df95aa32e4d9d7d897fd6/deployer/auth.py#L65-L67

@consideRatio, do you have anything configured under `hubs.domain`?

**Comment by consideRatio** [comment]
> @consideRatio, do you have anything configured under hubs.domain?

Yepp! I guess `_get_allowed_logout_url_list` isn't receiving my specified domain from the jmte.cluster.yaml config but from auth0 instead.

```
hubs:
  - name: prod
    domain: hub.jupytearth.org
    template: daskhub
    auth0:
      connection: github
```
